---
- name: Check Apache
  hosts: all
  tasks:
    - name: Check if {{ lookup('env','SERVICE_NAME') }}
      shell: systemctl status {{ lookup('env','SERVICE_NAME') }}
      register: svc_status
      failed_when: not(svc_status == 0)
