---
- name: Install HAProxy
  hosts: second
  become: yes
  vars_files:
    - secret
  roles:
      - role: haproxy
        haproxy_user: haproxy
        haproxy_pass: haproxy
        haproxy_conf: |
          listen web
              mode http
              bind *:80
              default-server port 80
              server web 12e.lab.int:8080 check
