---
# tasks file for apache-php

- name: Install Apache server
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Install PHP module for Apache
  apt:
    name: libapache2-mod-php
    state: present
    update_cache: yes

- name: Copy Apache vhosts configuration files
  template:
    src: vhost.conf.j2
    dest: "{{ apache_conf_path }}/sites-available/vhost.conf"
  notify: Restart Apache

- name: Create simlink
  file:
    src: "{{ apache_conf_path }}/sites-available/vhost.conf"
    dest: "{{ apache_conf_path }}/sites-enabled/vhost.conf"
    state: link

- name: Copy index.php with php_info
  template:
    src: index.php.j2
    dest: "{{ vhost_documentroot }}/index.php"

- name: Service Apache is enabled
  service:
    name: "{{ apache_service }}"
    enabled: yes
